### ISSUE TITLE
IllegalThreadStateException when attempting scan

### ISSUE THREAD

**Issue by theking2** [angryip/ipscan#168]
An IllegalThreadStateException is raised when rescaning a subnet

**Comment by cw2k** [comment]
I can confirm this problem.
The trigger for that bug is enabling any king of **sorting columns**. 
So when I for example enable **sort for IP** and then click 'Start' scan I got:
![image](https://user-images.githubusercontent.com/3834079/56097504-6cfc8e00-5ef5-11e9-9100-af5aad449470.png)
after this anytime further click 'Start' scan brings the error:
IllegalThreadStateException

**Comment by angryziber** [comment]
I suspect this has been fixed in 3.6.2.
Can you please confirm?

**Comment by theking2** [comment]
Confirm
