### ISSUE TITLE
Installer does not detect AdoptOpenJDK builds as valid java install

### ISSUE THREAD

**Issue by aaroneg** [angryip/ipscan#210]
Test:
Install OpenJDK13U **x86** with the following options checked in the installer

- [X] Add to path
- [X] Associate .jar
- [X] Set JAVA_HOME variable
- [ ] JavaSoft (Oracle) registry keys

Result: FAIL

- `ipscan-3.6.1-setup.exe` prompts for JRE 1.7.0
- Software fails to launch with error referencing Java 8 or newer being required
---------
Test:
Install OpenJDK13U **x86** with the following options checked in the installer

- [X] Add to path
- [X] Associate .jar
- [x] Set JAVA_HOME variable
- [X] JavaSoft (Oracle) registry keys

Result: PASS

- Installer creates no prompts
- Software launches correctly
---------
Test:
Install OpenJDK13U **x86_64** with the following options checked in the installer

- [X] Add to path
- [X] Associate .jar
- [X] Set JAVA_HOME variable
- [ ] JavaSoft (Oracle) registry keys

Result: FAIL

- `ipscan-3.6.1-setup.exe` prompts for JRE 1.7.0
- Software fails to launch with error referencing Java 8 or newer being required

---------
Test:
Install OpenJDK13U **x86_64** with the following options checked in the installer

- [X] Add to path
- [X] Associate .jar
- [X] Set JAVA_HOME variable
- [X] JavaSoft (Oracle) registry keys

Result: FAIL

- `ipscan-3.6.1-setup.exe` complains that the registry refers to a nonexistent JRE or a corrupted runtime, even though it is not corrupt or missing.
- Setup incorrectly installs 32 bit version 
- Software fails to launch with error referencing loading 32bit libraries on a 64 bit jvm
- directly-downloaded `ipscan-win64-3.6.1.exe` launches with no problems

---------

I hope this provides enough detail to help pinpoint the problems, but please let me know if there's any other testing i can do.

**Comment by angryziber** [comment]
Thanks for the detailed testing.

Yes, Angry IP Scanner uses Launch4j to generate an exe file for Windows.
Launch4j uses Windows Registry to find the installed Java and check it's version, that's why you need to have `JavaSoft (Oracle) registry keys` option enabled while using the AdoptOpenJDK installer.

Of course, you will also need ipscan binary for the matching architecture. AdoptOpenJDK provides a 64-bit Java by default, so that `ipscan-win64*.exe` is needed.

However, there's a valid point that the installer is more outdated. I forgot to update the JVM detection executable. Will need to fix that.

**Comment by aaroneg** [comment]
Thanks for taking a look at it!
